# Beast Autoclicker configuration

mode = "hold"  # "hold" or "toggle"
start_paused = false

# Human-like CPS range
min_cps = 10
max_cps = 15

# Every ~N clicks, insert a tiny micro pause to be human-like
micro_pause_every = 45      # base; real value jittered ±30%
micro_pause_ms_min = 60
micro_pause_ms_max = 140

# Jittering the delay further (in milliseconds)
extra_jitter_ms_min = -6
extra_jitter_ms_max = 9

[ui]
enabled = true
refresh_hz = 8

[hotkeys]
toggle_left = "f6"
toggle_right = "f7"
switch_mode = "f8"
pause_resume = "f9"
quit = "esc"
